name: CMake Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build Solver (Library)
      run: |
        mkdir -p solver_application/build
        cmake -S solver_application -B solver_application/build
        cmake --build solver_application/build --parallel

    - name: Build HelloWorld (App)
      run: |
        mkdir -p hello_world_application/build
        cmake -S hello_world_application -B hello_world_application/build
        cmake --build hello_world_application/build --parallel

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Build Solver (Library)
      run: |
        mkdir solver_application\build
        cmake -G "Visual Studio 17 2022" -A x64 -S solver_application -B solver_application\build
        cmake --build solver_application\build --config Release

    - name: Build HelloWorld (App)
      run: |
        mkdir hello_world_application\build
        cmake -G "Visual Studio 17 2022" -A x64 -S hello_world_application -B hello_world_application\build
        cmake --build hello_world_application\build --config Release
