name: CMake Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.25.0'

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++ make

    - name: Configure Project
      run: |
        mkdir build
        cd build
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cmake .. -G "Visual Studio 17 2022"
        else
          cmake ..
        fi

    - name: Build All Targets
      run: |
        cd build
        cmake --build . --config ${{ matrix.configuration }}

    - name: Test Executables (Optional) # Только для Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        ./hello_world_application/hello_world_app
        ./solver_application/solver_app

    - name: Upload Artifacts (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}-${{ matrix.configuration }}
        path: build/
